/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package App;

import javax.swing.JOptionPane;

/**
 *
 * @author Dumisani
 */
public class Availabletutor_page extends javax.swing.JFrame {

    /** Creates new form Availabletutor_page */
    public Availabletutor_page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        requesttutor2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        requesttutor4 = new javax.swing.JButton();
        requesttutor3 = new javax.swing.JButton();
        requesttutor1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        availtutorgethelp_btn = new javax.swing.JButton();
        availtutorback_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("WE TEACH. YOU LEARN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Available Tutor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Subject: Maths Lit");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sesion: One on One & Group");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tutor Name: Mrs A.Klerk");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        requesttutor2.setBackground(new java.awt.Color(255, 255, 255));
        requesttutor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requesttutor2.setForeground(new java.awt.Color(0, 153, 255));
        requesttutor2.setText("Request Tutor");
        requesttutor2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requesttutor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttutor2ActionPerformed(evt);
            }
        });
        jPanel1.add(requesttutor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tutor Name: Miss S.Motaung");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tutor Name: Mr J.Perterson");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tutor Name: Miss P.Van De Welt");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Subject: Business Studies");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Subject: Geography");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Subject: Business Studies");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Sesion: One on One & Group");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Sesion: One on One & Group");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Sesion: One on One & Group");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        requesttutor4.setBackground(new java.awt.Color(255, 255, 255));
        requesttutor4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requesttutor4.setForeground(new java.awt.Color(0, 153, 255));
        requesttutor4.setText("Request Tutor");
        requesttutor4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requesttutor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttutor4ActionPerformed(evt);
            }
        });
        jPanel1.add(requesttutor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        requesttutor3.setBackground(new java.awt.Color(255, 255, 255));
        requesttutor3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requesttutor3.setForeground(new java.awt.Color(0, 153, 255));
        requesttutor3.setText("Request Tutor");
        requesttutor3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requesttutor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttutor3ActionPerformed(evt);
            }
        });
        jPanel1.add(requesttutor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        requesttutor1.setBackground(new java.awt.Color(255, 255, 255));
        requesttutor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requesttutor1.setForeground(new java.awt.Color(0, 153, 255));
        requesttutor1.setText("Request Tutor");
        requesttutor1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requesttutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttutor1ActionPerformed(evt);
            }
        });
        jPanel1.add(requesttutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Please make sure you request the right tutor. ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("All our tutors are qualified and are verified by the Department of Edication. ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        availtutorgethelp_btn.setBackground(new java.awt.Color(204, 204, 204));
        availtutorgethelp_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        availtutorgethelp_btn.setForeground(new java.awt.Color(0, 0, 0));
        availtutorgethelp_btn.setText("Get Help");
        availtutorgethelp_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        availtutorgethelp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availtutorgethelp_btnActionPerformed(evt);
            }
        });
        jPanel1.add(availtutorgethelp_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        availtutorback_btn.setBackground(new java.awt.Color(204, 204, 204));
        availtutorback_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        availtutorback_btn.setForeground(new java.awt.Color(0, 0, 0));
        availtutorback_btn.setText("Back");
        availtutorback_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        availtutorback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availtutorback_btnActionPerformed(evt);
            }
        });
        jPanel1.add(availtutorback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requesttutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttutor1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have requested a Tutor. We will notify you with further details.");
    }//GEN-LAST:event_requesttutor1ActionPerformed

    private void requesttutor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttutor2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have requested a Tutor. We will notify you with further deatils.");
    }//GEN-LAST:event_requesttutor2ActionPerformed

    private void requesttutor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttutor3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You have requested a Tutor. We will notify you with further details.");
    }//GEN-LAST:event_requesttutor3ActionPerformed

    private void requesttutor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttutor4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You have requested a Tutor. We will notify you with further deatils.");
    }//GEN-LAST:event_requesttutor4ActionPerformed

    private void availtutorgethelp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availtutorgethelp_btnActionPerformed
        // TODO add your handling code here:
        Gethelp_page open = new Gethelp_page();
        open.show();
        this.dispose();
    }//GEN-LAST:event_availtutorgethelp_btnActionPerformed

    private void availtutorback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availtutorback_btnActionPerformed
        // TODO add your handling code here:
         Student_mainmenu open = new Student_mainmenu();
        open.show();
        this.dispose();
    }//GEN-LAST:event_availtutorback_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Availabletutor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Availabletutor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Availabletutor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Availabletutor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Availabletutor_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availtutorback_btn;
    private javax.swing.JButton availtutorgethelp_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton requesttutor1;
    private javax.swing.JButton requesttutor2;
    private javax.swing.JButton requesttutor3;
    private javax.swing.JButton requesttutor4;
    // End of variables declaration//GEN-END:variables

}
