/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

/**
 *
 * @author Dumisani
 */
public class Demoshowoff extends javax.swing.JFrame {

    /**
     * Creates new form Demoshowoff
     */
    public Demoshowoff() {
        initComponents();
        request_panel.setVisible(false);
        gethelp_panel.setVisible(false);
        submit_panel.setVisible(false);
        logout_panel.setVisible(false);
        close_label.setVisible(false);
        request_label.setVisible(false);
         submit_label.setVisible(false);
          gethelp_label.setVisible(false);
           logout_label.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        request_panel = new javax.swing.JPanel();
        request_label = new javax.swing.JLabel();
        gethelp_panel = new javax.swing.JPanel();
        gethelp_label = new javax.swing.JLabel();
        submit_panel = new javax.swing.JPanel();
        submit_label = new javax.swing.JLabel();
        logout_panel = new javax.swing.JPanel();
        logout_label = new javax.swing.JLabel();
        close_label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dumisani\\Downloads\\icons8-menu-30.png")); // NOI18N
        jLabel2.setText("Menu");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 60));

        request_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        request_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        request_label.setText("request tutor");
        request_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        request_panel.add(request_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(request_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 40));

        gethelp_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gethelp_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gethelp_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gethelp_label.setText("get help");
        gethelp_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gethelp_panel.add(gethelp_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(gethelp_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 40));

        submit_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submit_label.setText("submit");
        submit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_panel.add(submit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(submit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, 40));

        logout_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout_label.setText("logout");
        logout_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_panel.add(logout_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(logout_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 280, 40));

        close_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        close_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dumisani\\Downloads\\icons8-close-35.png")); // NOI18N
        close_label.setText("close");
        close_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
        });
        jPanel1.add(close_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(204, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 143, 200, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
        // TODO add your handling code here:
        menu_tab.setVisible(false);
        request_panel.setVisible(false);
        gethelp_panel.setVisible(false);
        submit_panel.setVisible(false);
        logout_panel.setVisible(false);
        close_label.setVisible(false);
        request_label.setVisible(false);
        submit_label.setVisible(false);
        gethelp_label.setVisible(false);
        logout_label.setVisible(false);
    }//GEN-LAST:event_close_labelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        menu_tab.setVisible(true);
        request_panel.setVisible(true);
        gethelp_panel.setVisible(true);
        submit_panel.setVisible(true);
        logout_panel.setVisible(true);
        close_label.setVisible(true);
        request_label.setVisible(true);
        submit_label.setVisible(true);
        gethelp_label.setVisible(true);
        logout_label.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demoshowoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demoshowoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demoshowoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demoshowoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demoshowoff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_label;
    private javax.swing.JLabel gethelp_label;
    private javax.swing.JPanel gethelp_panel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logout_label;
    private javax.swing.JPanel logout_panel;
    private javax.swing.JLabel request_label;
    private javax.swing.JPanel request_panel;
    private javax.swing.JLabel submit_label;
    private javax.swing.JPanel submit_panel;
    // End of variables declaration//GEN-END:variables

    private static class menu_tab {

        private static void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public menu_tab() {
        }
    }
}
