/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import javax.swing.JOptionPane;

/**
 *
 * @author Dumisani
 */
public class Registation_form extends javax.swing.JFrame {

    /**
     * Creates new form Registation_form
     */
    public Registation_form() {
        initComponents();
    //required_name.setVisible(false);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        required_name11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tsname = new javax.swing.JTextField();
        tsid = new javax.swing.JTextField();
        tscontact = new javax.swing.JTextField();
        tsemail = new javax.swing.JTextField();
        Passwordfield = new javax.swing.JPasswordField();
        ConfirmPfield = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        tscombo = new javax.swing.JComboBox<>();
        tcombo = new javax.swing.JComboBox<>();
        scombo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        required_name = new javax.swing.JLabel();
        required_name1 = new javax.swing.JLabel();
        required_name2 = new javax.swing.JLabel();
        required_name3 = new javax.swing.JLabel();
        required_name4 = new javax.swing.JLabel();
        required_name5 = new javax.swing.JLabel();
        required_name6 = new javax.swing.JLabel();
        required_name7 = new javax.swing.JLabel();
        required_name8 = new javax.swing.JLabel();
        required_name9 = new javax.swing.JLabel();
        required_name10 = new javax.swing.JLabel();
        required_name12 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        jPasswordField2.setText("jPasswordField2");

        required_name11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name11.setForeground(new java.awt.Color(255, 0, 0));
        required_name11.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("WE TEACH. YOU LEARN.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTER HERE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Surname & Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 208, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contact No.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 248, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 301, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Specify Tutor or Student");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 347, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 391, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Confirm password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 437, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Subject you will be tutoring");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 484, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Subject you are applying to be tutored for");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 534, -1, -1));

        tsname.setBackground(new java.awt.Color(255, 255, 255));
        tsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsnameActionPerformed(evt);
            }
        });
        jPanel1.add(tsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 166, 172, -1));

        tsid.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 208, 172, -1));

        tscontact.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tscontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 248, 172, -1));

        tsemail.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tsemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 301, 172, -1));

        Passwordfield.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 391, 178, -1));

        ConfirmPfield.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ConfirmPfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 437, 178, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Confirm registration");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 590, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back ");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 620, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MR", "MRS", "Miss" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 116, -1, -1));

        tscombo.setBackground(new java.awt.Color(255, 255, 255));
        tscombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tscombo.setForeground(new java.awt.Color(0, 0, 0));
        tscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specify", "Tutor", "Student" }));
        jPanel1.add(tscombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 347, -1, -1));

        tcombo.setBackground(new java.awt.Color(255, 255, 255));
        tcombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcombo.setForeground(new java.awt.Color(0, 0, 0));
        tcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select if tutor", "Maths", "Maths Lit", "English", "Accounting", "Business Studies", "Economics", "Physical Science", "Life Science", "Geography", "History", "Tourism" }));
        jPanel1.add(tcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 481, -1, -1));

        scombo.setBackground(new java.awt.Color(255, 255, 255));
        scombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scombo.setForeground(new java.awt.Color(0, 0, 0));
        scombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select if student", "Maths", "Maths Lit", "English", "Accounting", "Business Studies", "Economics", "Physical Science", "Life Science", "Geography", "History", "Tourism" }));
        jPanel1.add(scombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 531, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Clear");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 620, -1, -1));

        required_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name.setForeground(new java.awt.Color(255, 0, 0));
        required_name.setText("*");
        jPanel1.add(required_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 27, -1));

        required_name1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name1.setForeground(new java.awt.Color(255, 0, 0));
        required_name1.setText("*");
        jPanel1.add(required_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 27, -1));

        required_name2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name2.setForeground(new java.awt.Color(255, 0, 0));
        required_name2.setText("*");
        jPanel1.add(required_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 27, -1));

        required_name3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name3.setForeground(new java.awt.Color(255, 0, 0));
        required_name3.setText("*");
        jPanel1.add(required_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 27, -1));

        required_name4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name4.setForeground(new java.awt.Color(255, 0, 0));
        required_name4.setText("*");
        jPanel1.add(required_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 27, -1));

        required_name5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name5.setForeground(new java.awt.Color(255, 0, 0));
        required_name5.setText("*");
        jPanel1.add(required_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 27, -1));

        required_name6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name6.setForeground(new java.awt.Color(255, 0, 0));
        required_name6.setText("*");
        jPanel1.add(required_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 27, 20));

        required_name7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name7.setForeground(new java.awt.Color(255, 0, 0));
        required_name7.setText("*");
        jPanel1.add(required_name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 27, -1));

        required_name8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name8.setForeground(new java.awt.Color(255, 0, 0));
        required_name8.setText("*");
        jPanel1.add(required_name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 27, -1));

        required_name9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name9.setForeground(new java.awt.Color(255, 0, 0));
        required_name9.setText("*");
        jPanel1.add(required_name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 27, -1));

        required_name10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name10.setForeground(new java.awt.Color(255, 0, 0));
        required_name10.setText("*");
        jPanel1.add(required_name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 27, -1));

        required_name12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        required_name12.setForeground(new java.awt.Color(255, 0, 0));
        required_name12.setText("*");
        jPanel1.add(required_name12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 27, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tsnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: Confirm registration Button
        String Name=tsname.getText().toString();
        String ID=tsid.getText().toString();
        String Phone=tscontact.getText().toString();
        String Email=tsemail.getText().toString();
        String Password=Passwordfield.getText().toString();
        String Confirm=ConfirmPfield.getText().toString();
        if(ID.equals("") ||Phone.equals("") || Email.equals("") || Password.equals("")
                || Confirm.equals("") || Name.equals("")){
            JOptionPane.showMessageDialog(null,"Fill in the required feilds");
            required_name.setVisible(true);
        
        
        
        } else{
             JOptionPane.showMessageDialog(null,"Application sent, lookout for our Email.");
    }//GEN-LAST:event_jButton1ActionPerformed
  
    
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: Clear button 
        tsname.setText(null);
        tsid.setText(null);
        tscontact.setText(null);
        tsemail.setText(null);
        ConfirmPfield.setText(null);
        Passwordfield.setText(null);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Login_form open = new Login_form();
        open.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registation_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registation_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registation_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registation_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registation_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPfield;
    private javax.swing.JPasswordField Passwordfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel required_name;
    private javax.swing.JLabel required_name1;
    private javax.swing.JLabel required_name10;
    private javax.swing.JLabel required_name11;
    private javax.swing.JLabel required_name12;
    private javax.swing.JLabel required_name2;
    private javax.swing.JLabel required_name3;
    private javax.swing.JLabel required_name4;
    private javax.swing.JLabel required_name5;
    private javax.swing.JLabel required_name6;
    private javax.swing.JLabel required_name7;
    private javax.swing.JLabel required_name8;
    private javax.swing.JLabel required_name9;
    private javax.swing.JComboBox<String> scombo;
    private javax.swing.JComboBox<String> tcombo;
    private javax.swing.JComboBox<String> tscombo;
    private javax.swing.JTextField tscontact;
    private javax.swing.JTextField tsemail;
    private javax.swing.JTextField tsid;
    private javax.swing.JTextField tsname;
    // End of variables declaration//GEN-END:variables
}
