/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import javax.swing.JOptionPane;

/**
 *
 * @author Dumisani
 */
public class Tutorrequest_page extends javax.swing.JFrame {

    /**
     * Creates new form Tutorrequest_page
     */
    public Tutorrequest_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Acceptbtn3 = new javax.swing.JButton();
        Declinebtn3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Acceptbtn2 = new javax.swing.JButton();
        Declinebtn2 = new javax.swing.JButton();
        Declinebtn4 = new javax.swing.JButton();
        Declinebtn1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Acceptbtn4 = new javax.swing.JButton();
        Acceptbtn1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tutorrequest_backbtn = new javax.swing.JButton();
        tutorrequest_gethelpbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("WE TEACH. YOU LEARN.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Tutor Requests:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subject: Life Sciences ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Session: One on One");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Student Name: Lebogang Masango");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Acceptbtn3.setBackground(new java.awt.Color(255, 255, 255));
        Acceptbtn3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Acceptbtn3.setForeground(new java.awt.Color(0, 153, 255));
        Acceptbtn3.setText("Accept");
        Acceptbtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Acceptbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceptbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(Acceptbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 50, 30));

        Declinebtn3.setBackground(new java.awt.Color(255, 255, 255));
        Declinebtn3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Declinebtn3.setForeground(new java.awt.Color(255, 0, 51));
        Declinebtn3.setText("Decline");
        Declinebtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Declinebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Declinebtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(Declinebtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 60, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Student Name: Lebogang Masango");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Subject: Life Sciences ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Session: One on One");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        Acceptbtn2.setBackground(new java.awt.Color(255, 255, 255));
        Acceptbtn2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Acceptbtn2.setForeground(new java.awt.Color(0, 153, 255));
        Acceptbtn2.setText("Accept");
        Acceptbtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Acceptbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceptbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(Acceptbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 50, 30));

        Declinebtn2.setBackground(new java.awt.Color(255, 255, 255));
        Declinebtn2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Declinebtn2.setForeground(new java.awt.Color(255, 0, 51));
        Declinebtn2.setText("Decline");
        Declinebtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Declinebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Declinebtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(Declinebtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 60, 30));

        Declinebtn4.setBackground(new java.awt.Color(255, 255, 255));
        Declinebtn4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Declinebtn4.setForeground(new java.awt.Color(255, 0, 51));
        Declinebtn4.setText("Decline");
        Declinebtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Declinebtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Declinebtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(Declinebtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 60, 30));

        Declinebtn1.setBackground(new java.awt.Color(255, 255, 255));
        Declinebtn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Declinebtn1.setForeground(new java.awt.Color(255, 0, 51));
        Declinebtn1.setText("Decline");
        Declinebtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Declinebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Declinebtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Declinebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Decline");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 30));

        Acceptbtn4.setBackground(new java.awt.Color(255, 255, 255));
        Acceptbtn4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Acceptbtn4.setForeground(new java.awt.Color(0, 153, 255));
        Acceptbtn4.setText("Accept");
        Acceptbtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Acceptbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceptbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(Acceptbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 50, 30));

        Acceptbtn1.setBackground(new java.awt.Color(255, 255, 255));
        Acceptbtn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Acceptbtn1.setForeground(new java.awt.Color(0, 153, 255));
        Acceptbtn1.setText("Accept");
        Acceptbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Acceptbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceptbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Acceptbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 50, 30));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 255));
        jButton10.setText("Accept");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 50, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Session: One on One");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Session: One on One");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Subject: Life Sciences ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Subject: Life Sciences ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Student Name: Lebogang Masango");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Student Name: Lebogang Masango");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tutorrequest_backbtn.setBackground(new java.awt.Color(204, 204, 204));
        tutorrequest_backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorrequest_backbtn.setForeground(new java.awt.Color(0, 0, 0));
        tutorrequest_backbtn.setText("Back");
        tutorrequest_backbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorrequest_backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorrequest_backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorrequest_backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 50, -1));

        tutorrequest_gethelpbtn.setBackground(new java.awt.Color(204, 204, 204));
        tutorrequest_gethelpbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorrequest_gethelpbtn.setForeground(new java.awt.Color(0, 0, 0));
        tutorrequest_gethelpbtn.setText("Get Help");
        tutorrequest_gethelpbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorrequest_gethelpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorrequest_gethelpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorrequest_gethelpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Declinebtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Declinebtn3ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have declined the request.");
    }//GEN-LAST:event_Declinebtn3ActionPerformed

    private void Declinebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Declinebtn2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have declined the request.");
    }//GEN-LAST:event_Declinebtn2ActionPerformed

    private void Declinebtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Declinebtn4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have declined the request.");
    }//GEN-LAST:event_Declinebtn4ActionPerformed

    private void Declinebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Declinebtn1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You have declined the request.");
    }//GEN-LAST:event_Declinebtn1ActionPerformed
     
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Acceptbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceptbtn2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for accepting the request, We will communicate further details.");
    }//GEN-LAST:event_Acceptbtn2ActionPerformed

    private void Acceptbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceptbtn1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for accepting the request, We will communicate further details.");
    }//GEN-LAST:event_Acceptbtn1ActionPerformed

    private void Acceptbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceptbtn3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for accepting the request, We will communicate further details.");
    }//GEN-LAST:event_Acceptbtn3ActionPerformed

    private void Acceptbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceptbtn4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for accepting the request, We will communicate further details.");
    }//GEN-LAST:event_Acceptbtn4ActionPerformed

    private void tutorrequest_backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorrequest_backbtnActionPerformed
        // TODO add your handling code here:
         Tutor_Mainmenu open = new Tutor_Mainmenu();
        open.show();
        this.dispose();
    }//GEN-LAST:event_tutorrequest_backbtnActionPerformed

    private void tutorrequest_gethelpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorrequest_gethelpbtnActionPerformed
        // TODO add your handling code here:
         Gethelp_page open = new Gethelp_page();
        open.show();
        this.dispose();
        
    }//GEN-LAST:event_tutorrequest_gethelpbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorrequest_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorrequest_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorrequest_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorrequest_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorrequest_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceptbtn1;
    private javax.swing.JButton Acceptbtn2;
    private javax.swing.JButton Acceptbtn3;
    private javax.swing.JButton Acceptbtn4;
    private javax.swing.JButton Declinebtn1;
    private javax.swing.JButton Declinebtn2;
    private javax.swing.JButton Declinebtn3;
    private javax.swing.JButton Declinebtn4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tutorrequest_backbtn;
    private javax.swing.JButton tutorrequest_gethelpbtn;
    // End of variables declaration//GEN-END:variables
}
