package App;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dumisani
 */
public class Tutor_Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Tutor_Mainmenu
     */
    public Tutor_Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Entersession_2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Entersession_3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Entersession_1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tutorgethelp_btn = new javax.swing.JButton();
        tutorlogout_btn = new javax.swing.JButton();
        tutorrequests_btn = new javax.swing.JButton();
        tutorback_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("WE TEACH. YOU LEARN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Subject: Physical Science");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Time: 15:30pm");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date: 17 Feb 2024");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        Entersession_2.setBackground(new java.awt.Color(255, 255, 255));
        Entersession_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entersession_2.setForeground(new java.awt.Color(0, 153, 255));
        Entersession_2.setText("Enter Session");
        Entersession_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entersession_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entersession_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Entersession_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Session: Group Session");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Subject: Economics");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Time: 09:00am");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Date: 25 Feb 2024");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        Entersession_3.setBackground(new java.awt.Color(255, 255, 255));
        Entersession_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entersession_3.setForeground(new java.awt.Color(0, 153, 255));
        Entersession_3.setText("Enter Session");
        Entersession_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entersession_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entersession_3ActionPerformed(evt);
            }
        });
        jPanel3.add(Entersession_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Session: One on One");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 190, 260));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Subject: Mathematics");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Time: 10:00am");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Date: 10 Feb 2024");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        Entersession_1.setBackground(new java.awt.Color(255, 255, 255));
        Entersession_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entersession_1.setForeground(new java.awt.Color(0, 153, 255));
        Entersession_1.setText("Enter Session");
        Entersession_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entersession_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entersession_1ActionPerformed(evt);
            }
        });
        jPanel4.add(Entersession_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Session: One on One");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 260));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Your tutor sessions for the month of February 2024 are as show below. ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        tutorgethelp_btn.setBackground(new java.awt.Color(204, 204, 204));
        tutorgethelp_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorgethelp_btn.setForeground(new java.awt.Color(0, 0, 0));
        tutorgethelp_btn.setText("Get Help");
        tutorgethelp_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorgethelp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorgethelp_btnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorgethelp_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, -1));

        tutorlogout_btn.setBackground(new java.awt.Color(204, 204, 204));
        tutorlogout_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorlogout_btn.setForeground(new java.awt.Color(0, 0, 0));
        tutorlogout_btn.setText("Log Out");
        tutorlogout_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorlogout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorlogout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorlogout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        tutorrequests_btn.setBackground(new java.awt.Color(204, 204, 204));
        tutorrequests_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorrequests_btn.setForeground(new java.awt.Color(0, 0, 0));
        tutorrequests_btn.setText("Tutor requests");
        tutorrequests_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorrequests_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorrequests_btnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorrequests_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, -1));

        tutorback_btn.setBackground(new java.awt.Color(204, 204, 204));
        tutorback_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorback_btn.setForeground(new java.awt.Color(0, 0, 0));
        tutorback_btn.setText("Back");
        tutorback_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorback_btnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entersession_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entersession_1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You will soon be directed to your session, Please Wait.");
    }//GEN-LAST:event_Entersession_1ActionPerformed

    private void Entersession_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entersession_2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Your session starts in an hour, Come back in an hour.");
    }//GEN-LAST:event_Entersession_2ActionPerformed

    private void Entersession_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entersession_3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, ".");
    }//GEN-LAST:event_Entersession_3ActionPerformed

    private void tutorgethelp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorgethelp_btnActionPerformed
        // TODO add your handling code here:
         Gethelp_page open = new Gethelp_page();
        open.show();
        this.dispose();
    }//GEN-LAST:event_tutorgethelp_btnActionPerformed

    private void tutorback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorback_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorback_btnActionPerformed

    private void tutorlogout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorlogout_btnActionPerformed
        // TODO add your handling code here:
         Login_form open = new Login_form();
        open.show();
        this.dispose();
    }//GEN-LAST:event_tutorlogout_btnActionPerformed

    private void tutorrequests_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorrequests_btnActionPerformed
        // TODO add your handling code here:
         Tutorrequest_page open = new Tutorrequest_page();
        open.show();
        this.dispose();
    }//GEN-LAST:event_tutorrequests_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutor_Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutor_Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutor_Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutor_Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutor_Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entersession_1;
    private javax.swing.JButton Entersession_2;
    private javax.swing.JButton Entersession_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton tutorback_btn;
    private javax.swing.JButton tutorgethelp_btn;
    private javax.swing.JButton tutorlogout_btn;
    private javax.swing.JButton tutorrequests_btn;
    // End of variables declaration//GEN-END:variables
}
